In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns 

from scipy.stats import norm

In [2]:
ames = pd.read_csv('./data/ames_prices.csv')
ames.head(10)

,Order,PID,area,price,MS.SubClass,MS.Zoning,Lot.Frontage,Lot.Area,Street,Alley,...,Screen.Porch,Pool.Area,Pool.QC,Fence,Misc.Feature,Misc.Val,Mo.Sold,Yr.Sold,Sale.Type,Sale.Condition
0,1,526301100,1656,215000,20,RL,141.0,31770,Pave,NaN,...,0,0,NaN,NaN,NaN,0,5,2010,WD,Normal
1,2,526350040,896,105000,20,RH,80.0,11622,Pave,NaN,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
2,3,526351010,1329,172000,20,RL,81.0,14267,Pave,NaN,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
3,4,526353030,2110,244000,20,RL,93.0,11160,Pave,NaN,...,0,0,NaN,NaN,NaN,0,4,2010,WD,Normal
4,5,527105010,1629,189900,60,RL,74.0,13830,Pave,NaN,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
5,6,527105030,1604,195500,60,RL,78.0,9978,Pave,NaN,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
6,7,527127150,1338,213500,120,RL,41.0,4920,Pave,NaN,...,0,0,NaN,NaN,NaN,0,4,2010,WD,Normal
7,8,527145080,1280,191500,120,RL,43.0,5005,Pave,NaN,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal
8,9,527146030,1616,236500,120,RL,39.0,5389,Pave,NaN,...,0,0,NaN,NaN,NaN,0,3,2010,WD,Normal
9,10,527162130,1804,189000,60,RL,60.0,7500,Pave,NaN,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal

In [3]:
meta = pd.read_csv('./data/metabric.csv')
meta.head(10)

,Age at Diagnosis,Type of Breast Surgery,Cancer Type,Chemotherapy,Hormone Therapy,Lymph nodes examined positive,Mutation Count,Nottingham prognostic index,Overall Survival (Months),Overall Survival Status,Radio Therapy,TMB (nonsynonymous),Tumor Size,Tumor Stage
0,43.19,BREAST CONSERVING,Breast Cancer,NO,YES,0.0,2.0,4.020,84.633333,0:LIVING,YES,2.615035,10.0,1.0
1,48.87,MASTECTOMY,Breast Cancer,YES,YES,1.0,2.0,4.030,163.700000,1:DECEASED,NO,2.615035,15.0,2.0
2,47.68,MASTECTOMY,Breast Cancer,YES,YES,3.0,1.0,4.050,164.933333,0:LIVING,YES,1.307518,25.0,2.0
3,76.97,MASTECTOMY,Breast Cancer,YES,YES,8.0,2.0,6.080,41.366667,1:DECEASED,YES,2.615035,40.0,2.0
4,78.77,MASTECTOMY,Breast Cancer,NO,YES,0.0,4.0,4.062,7.800000,1:DECEASED,YES,5.230071,31.0,4.0
5,56.45,BREAST CONSERVING,Breast Cancer,YES,YES,1.0,4.0,4.020,164.333333,0:LIVING,YES,5.230071,10.0,2.0
6,89.08,BREAST CONSERVING,Breast Cancer,NO,YES,1.0,1.0,4.058,99.533333,1:DECEASED,YES,1.307518,29.0,2.0
7,86.41,BREAST CONSERVING,Breast Cancer,NO,YES,1.0,4.0,5.032,36.566667,1:DECEASED,YES,5.230071,16.0,2.0
8,84.22,MASTECTOMY,Breast Cancer,NO,NO,0.0,5.0,3.056,36.266667,1:DECEASED,NO,6.537589,28.0,2.0
9,85.49,MASTECTOMY,Breast Cancer,NO,YES,0.0,1.0,3.044,132.033333,1:DECEASED,YES,1.307518,22.0,4.0

In [4]:
data = pd.read_csv('./data/nhanes_data_17_18.csv')
data.head(10)

C:\Users\witze\AppData\Local\Temp\ipykernel_18756\2401364656.py:1: DtypeWarning: Columns (0: ServedActiveDutyInUsArmedForces) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('./data/nhanes_data_17_18.csv')

,SEQN,GeneralHealthCondition,EverBreastfedOrFedBreastmilk,AgeStoppedBreastfeedingdays,AgeFirstFedFormuladays,AgeStoppedReceivingFormuladays,AgeStartedOtherFoodbeverage,AgeFirstFedMilkdays,TypeOfMilkFirstFedWholeMilk,TypeOfMilkFirstFed2Milk,...,DaysSmokedCigsDuringPast30Days,AvgCigarettesdayDuringPast30Days,TriedToQuitSmoking,TimesStoppedSmokingCigarettes,HowLongWereYouAbleToStopSmoking,UnitOfMeasureDayweekmonthyear_2_SMQ,CurrentSelfreportedHeightInches,CurrentSelfreportedWeightPounds,TriedToLoseWeightInPastYear,TimesLost10LbsOrMoreToLoseWeight
0,93703.0,NaN,1.0,273.0,1.0,365.0,152.0,365.0,Whole or regular milk,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,93704.0,NaN,1.0,60.0,3.0,365.0,126.0,365.0,Whole or regular milk,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,93705.0,Good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,63.0,165.0,0.0,11 times or more
3,93706.0,Very good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,68.0,145.0,0.0,Never
4,93707.0,Good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,93708.0,Good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,60.0,118.0,0.0,Never
6,93709.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,30.0,5.0,0.0,NaN,NaN,NaN,62.0,200.0,0.0,6 to 10
7,93711.0,Very good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,69.0,142.0,0.0,Never
8,93712.0,Good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.0,2.0,1.0,10.0,4.0,Months,68.0,135.0,0.0,Never
9,93713.0,Very good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,30.0,15.0,1.0,3.0,1.0,Days,70.0,165.0,0.0,Never

In [5]:
ames['Central.Air'] = ames['Central.Air'].map({'Y': 1, 'N': 0})
ames['Central.Air'].mean()
#The estimated proportion of homes with central air is 0.933.

np.float64(0.9331058020477816)

In [6]:
rng = np.random.default_rng(42)

R = 2000
results = []

for t in range(R):
    idx = rng.integers(0, len(ames), size=len(ames))
    prop = ames['Central.Air'].iloc[idx].mean()
    results.append(prop)

#The rng seed I used was 42. I used 2000 bootstrap replications.

mean = np.mean(results)
standard_error = np.std(results, ddof=1)
standard_error

#The standard error is 0.00459.

np.float64(0.004590333440769273)

In [7]:
print(np.quantile(results, [0.05, 0.95]))
print(np.quantile(results, [0.025, 0.975]))
print(np.quantile(results, [0.005, 0.995]))

[0.92559727 0.94061433]
[0.92389078 0.94197952]
[0.92150171 0.9443686 ]

Ho: p = 0.9
Ha: p =/= 0.9
At every significance level a=0.1, a=0.05, and a=0.01, we reject the null hypothesis that p = 0.9. Every confidence interval excludes p=0.9.

In [8]:
area = np.arcsinh(ames['area'])
price = np.arcsinh(ames['price'])
cor = np.corrcoef(area, price)[0,1]

corrs = []
for t in range(R):
    idx = rng.integers(0, len(ames), size=len(ames))

    area_boot = area.iloc[idx]
    price_boot = price.iloc[idx]
    corr_boot = np.corrcoef(area_boot, price_boot)[0,1]
    corrs.append(corr_boot)

#The rng seed I used was 42. I used 2000 bootstrap replications.

stder = np.std(corrs, ddof=1)
stder

#The standard error is 0.01035

np.float64(0.010353429300189912)

In [9]:
print(np.quantile(corrs, [0.05, 0.95]))
print(np.quantile(corrs, [0.025, 0.975]))
print(np.quantile(corrs, [0.005, 0.995]))

[0.70599505 0.74037557]
[0.70250099 0.7442443 ]
[0.69582768 0.7488471 ]

Ho: p = 0. Ha: p =/= 0. 
At every significance level a=0.1, a=0.05, and a=0.01, we reject the null hypothesis that there is no correlation between area and price. 

Area and price must remain paired during resampling because of their correlation. If the bootstrap randomly assigns area and price without their pairs, this would alter the connection between each house and its price and create unstability in the data.

In [10]:
meta['Overall Survival (Months)'].mean()

np.float64(129.09429138744105)

In [11]:
rng = np.random.default_rng(42)

R = 2000
results = []

for t in range(R):
    idx = rng.integers(0, len(meta), size=len(meta))
    mean = meta['Overall Survival (Months)'].iloc[idx].mean()
    results.append(mean)

#The rng seed I used was 42. I used 2000 bootstrap replications.

standard_error = np.std(results, ddof=1)
print(standard_error)

#The standard error is 2.1358.

print(np.quantile(results, [0.05, 0.95]))
print(np.quantile(results, [0.025, 0.975]))
print(np.quantile(results, [0.005, 0.995]))

2.135806001210453
[125.70154257 132.61022462]
[124.98355982 133.39589352]
[123.57614681 134.50288905]

Ho: u = 120. Ha: u =/= 120. 
At every significance level a=0.1, a=0.05, and a=0.01, we reject the null hypothesis that the mean survival in months is 120. 

The estimate of 129 months means that the average tested patient lived for 129 months. The confidence intervals represent the interval in which the true average months of survival lies, each one specifically increasing as our confidence increases. 

These results do not perfectly estimate unrestricted mean lifetime, as patients still alive have not been properly recorded. These results estimate the survival of the deceased patients.

In [12]:
subset = data[
    (data['AgeInYearsAtScreening'] >= 18) &
    (data['SleepHoursWeekdaysOrWorkdays'].notna())
]

nhanes = subset['SleepHoursWeekdaysOrWorkdays']

nhanes.mean()

np.float64(7.62124248496994)

In [13]:
rng = np.random.default_rng(42)

R = 2000
results = []

for t in range(R):
    idx = rng.integers(0, len(nhanes), size=len(nhanes))
    mean = nhanes.iloc[idx].mean()
    results.append(mean)

#The rng seed I used was 42. I used 2000 bootstrap replications.

standard_error = np.std(results, ddof=1)
print(standard_error)

#The standard error is 0.02275.

print(np.quantile(results, [0.05, 0.95]))
print(np.quantile(results, [0.025, 0.975]))
print(np.quantile(results, [0.005, 0.995]))

0.022750666141160076
[7.58271088 7.65804336]
[7.57605894 7.66478639]
[7.56257834 7.67590271]

Ho: u = 8
Ha: u =/= 8
At every significance level a=0.1, a=0.05, and a=0.01, we reject the null hypothesis that the average hours of sleep in adults in 8. 

Seeing how massive the sample size is, any difference is statistically significant. Practically, these differences are not significant because of how little this actually affects people. 

The results of this study aren't actually applicable to the United States or any general population because of how much the rules of proper sampling are ignored. This data can only be applied to the subjects in the sample data.